package com.androidharness.app.data.env

import android.system.Os
import com.androidharness.app.workspace.WorkspaceFs
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.withContext
import okhttp3.OkHttpClient
import okhttp3.Request
import org.apache.commons.compress.archivers.ar.ArArchiveInputStream
import org.apache.commons.compress.archivers.tar.TarArchiveInputStream
import org.apache.commons.compress.compressors.CompressorStreamFactory
import java.io.File
import java.io.FileOutputStream
import java.io.InputStream
import java.security.MessageDigest
import java.util.concurrent.TimeUnit
import java.util.zip.GZIPInputStream

internal const val CODEGRAPH_VERSION_MARKER = ".harness-codegraph-version"

internal object CodeGraphCommands {
    private fun quote(value: String): String = "'" + value.replace("'", "'\\''") + "'"

    const val version = "codegraph --no-color version"
    const val init = "codegraph --no-color init --yes ."
    const val sync = "codegraph --no-color sync ."
    const val reindex = "codegraph --no-color index ."
    const val uninit = "codegraph --no-color uninit --force ."

    fun explore(query: String): String = "codegraph --no-color explore ${quote(query)}"

    fun node(name: String?, file: String?, offset: Int?, limit: Int?): String = buildString {
        append("codegraph --no-color node")
        if (!file.isNullOrBlank()) append(" --file ").append(quote(file.trim()))
        if (offset != null) append(" --offset ").append(offset.coerceAtLeast(1))
        if (limit != null) append(" --limit ").append(limit.coerceIn(1, 2_000))
        if (!name.isNullOrBlank()) append(' ').append(quote(name.trim()))
    }

    fun impact(symbol: String, depth: Int): String =
        "codegraph --no-color impact --depth ${depth.coerceIn(1, 10)} ${quote(symbol.trim())}"

    fun affected(files: List<String>, depth: Int): String = buildString {
        append("codegraph --no-color affected --depth ").append(depth.coerceIn(1, 10))
        files.map { it.trim() }.filter { it.isNotEmpty() }.forEach { append(' ').append(quote(it)) }
    }

    /**
     * The `codegraph` entry point Harness installs into the prefix. The
     * upstream release archive bundles its own Node, but that binary is built
     * against glibc and cannot start on Android, so the launcher runs the
     * archive's JavaScript on the Termux-built Node 24 installed beside it.
     *
     * $0-relative on purpose: the same file is used from the app-private
     * prefix and from the shell-tier copy deployed under /data/local/tmp, and
     * only the first is known at write time. ELF exec is blocked for
     * app-private files, so the dynamic linker runs the runtime when present.
     */
    fun launcher(): String = """
        |#!/system/bin/sh
        |# auto-generated by AndroidHarness: runs CodeGraph's JS on the bundled Node 24.
        |case "${'$'}0" in
        |  */*) DIR="${'$'}{0%/*}" ;;
        |  *) DIR="." ;;
        |esac
        |PREFIX="${'$'}(cd "${'$'}DIR/.." && pwd)"
        |NODE="${'$'}PREFIX/codegraph/node/bin/node"
        |CLI="${'$'}PREFIX/codegraph/bundle/lib/dist/bin/codegraph.js"
        |if [ ! -f "${'$'}CLI" ] || [ ! -x "${'$'}NODE" ]; then
        |  echo "codegraph: the Harness-installed runtime is incomplete. Reinstall it from Settings, Code intelligence." >&2
        |  exit 127
        |fi
        |LINKER=
        |for c in /system/bin/linker64 /apex/com.android.runtime/bin/linker64 /system/bin/linker; do
        |  if [ -x "${'$'}c" ]; then LINKER="${'$'}c"; break; fi
        |done
        |if [ -n "${'$'}LINKER" ]; then
        |  exec "${'$'}LINKER" "${'$'}NODE" --liftoff-only --disable-warning=ExperimentalWarning "${'$'}CLI" "${'$'}@"
        |fi
        |exec "${'$'}NODE" --liftoff-only --disable-warning=ExperimentalWarning "${'$'}CLI" "${'$'}@"
        |""".trimMargin()
}

/**
 * Everything about *where* CodeGraph comes from.
 *
 * Android is not a published CodeGraph platform: the npm shim asks for
 * `codegraph-android-arm64` because Termux's Node reports `process.platform
 * == "android"`, and neither npm nor GitHub Releases ever publishes it
 * (colbymchenry/codegraph#1550). So Harness does not use npm at all here. It
 * takes the linux-arm64 release archive and keeps only the parts that carry
 * no platform assumption, the JavaScript and the tree-sitter WASM grammars,
 * plus the Termux-built Node that can actually run them.
 */
internal object CodeGraphProvision {
    private const val REPO = "colbymchenry/codegraph"

    /** The release archive whose payload is architecture-independent. */
    const val BUNDLE_ASSET = "codegraph-linux-arm64.tar.gz"

    /** Termux package carrying the Node 24 runtime CodeGraph is built against. */
    const val NODE_PACKAGE = "nodejs-lts"

    fun latestPageUrl(): String = "https://github.com/$REPO/releases/latest"

    fun apiLatestUrl(): String = "https://api.github.com/repos/$REPO/releases/latest"

    fun assetUrl(tag: String): String = "https://github.com/$REPO/releases/download/$tag/$BUNDLE_ASSET"

    fun sumsUrl(tag: String): String = "https://github.com/$REPO/releases/download/$tag/SHA256SUMS"

    /** Release tag from the `releases/latest` redirect target, without the API's rate limit. */
    fun tagFromRedirect(location: String?): String? {
        val raw = location?.substringAfterLast("/releases/tag/", "")?.trim()
        return raw?.takeIf { it.isNotEmpty() && it != location }
    }

    /** Release tag from the API's `tag_name` field. */
    fun tagFromApi(json: String): String? =
        Regex("\"tag_name\"\\s*:\\s*\"([^\"]+)\"").find(json)?.groupValues?.get(1)?.trim()?.takeIf { it.isNotEmpty() }

    /** Release tags are `vX.Y.Z`; accept a bare `X.Y.Z` too. */
    fun normalizeTag(raw: String?): String? {
        val tag = raw?.trim()?.takeIf { it.isNotEmpty() } ?: return null
        return if (tag.startsWith("v")) tag else "v$tag"
    }

    /** Expected SHA-256 of [asset] from a published SHA256SUMS file, or null when unlisted. */
    fun sha256For(sums: String, asset: String): String? = sums.lineSequence().mapNotNull { line ->
        val match = Regex("^([0-9a-fA-F]{64})\\s+\\*?(.+)$").find(line.trim()) ?: return@mapNotNull null
        if (match.groupValues[2].trim().substringAfterLast('/') == asset) match.groupValues[1].lowercase() else null
    }.firstOrNull()

    /** True when [candidate] is a later release than [installed], ignoring any pre-release suffix. */
    fun isNewer(candidate: String, installed: String): Boolean {
        fun parts(v: String) = v.substringBefore('-').substringBefore('+')
            .split('.').map { it.trim().toIntOrNull() ?: 0 }
        val a = parts(candidate)
        val b = parts(installed)
        for (i in 0 until maxOf(a.size, b.size)) {
            val diff = (a.getOrNull(i) ?: 0) - (b.getOrNull(i) ?: 0)
            if (diff != 0) return diff > 0
        }
        return false
    }

    /**
     * Prefix-relative path for a release archive entry worth keeping, or null
     * to skip it. The archive's own Node (`node`, ~116 MB, glibc) and native
     * kernel (`lib/kernel`, glibc) are dropped: the kernel is optional by
     * design and extraction falls back to the WASM grammars without it.
     * Sourcemaps and type declarations are development-only.
     */
    fun portablePath(entry: String): String? {
        val cleaned = entry.trim().removePrefix("./").removePrefix("/")
        if (cleaned.isEmpty()) return null
        // Validate every segment BEFORE dropping the archive's top-level
        // directory: checking afterwards would let "../lib/x" collapse into a
        // harmless-looking "lib/x" and escape the destination.
        val segments = cleaned.split('/')
        if (segments.any { it.isEmpty() || it == "." || it == ".." }) return null
        // Entries carry that directory, e.g. "codegraph-linux-arm64/lib/dist/index.js".
        val rel = segments.drop(1).joinToString("/")
        if (!rel.startsWith("lib/")) return null
        if (rel.startsWith("lib/kernel/")) return null
        if (rel.endsWith(".map") || rel.endsWith(".d.ts")) return null
        return rel
    }
}

data class CodeGraphState(
    val version: String? = null,
    /** Newest published release, once a check has run. */
    val latest: String? = null,
    val busy: Boolean = false,
    val action: String? = null,
    val message: String? = null,
    val failed: Boolean = false,
) {
    val updateAvailable: Boolean
        get() = version != null && latest != null && CodeGraphProvision.isNewer(latest, version)
}

data class CodeGraphCommandResult(val ok: Boolean, val output: String)

class CodeGraphManager(
    private val linuxEnv: LinuxEnvironmentManager,
    private val shellRouter: ShellTierRouter,
) {
    // Release archives run to ~130 MB, so the read timeout is generous: the
    // call timeout is what bounds a genuinely stalled connection.
    private val client = OkHttpClient.Builder()
        .connectTimeout(30, TimeUnit.SECONDS)
        .readTimeout(5, TimeUnit.MINUTES)
        .callTimeout(30, TimeUnit.MINUTES)
        .build()

    private val marker get() = File(linuxEnv.prefix, CODEGRAPH_VERSION_MARKER)
    private val binary get() = File(linuxEnv.prefix, "bin/codegraph")
    private val home get() = File(linuxEnv.prefix, "home").apply { mkdirs() }
    private val root get() = File(linuxEnv.prefix, "codegraph")
    private val nodeBinary get() = File(root, "node/bin/node")
    private val bundleLib get() = File(root, "bundle/lib")

    private val _state = MutableStateFlow(CodeGraphState(version = markerVersion()))
    val state: StateFlow<CodeGraphState> = _state

    fun isIndexed(workspace: WorkspaceFs?): Boolean =
        workspace?.shellRoot?.resolve(".codegraph")?.isDirectory == true

    fun isAvailable(workspace: WorkspaceFs): Boolean =
        linuxEnv.isReady && binary.exists() && isIndexed(workspace)

    suspend fun refresh(): CodeGraphState {
        if (!binary.exists() || !linuxEnv.isReady) {
            marker.delete()
            val next = CodeGraphState()
            _state.value = next
            return next
        }
        val result = run(CodeGraphCommands.version, home, 30_000, 4_000)
        val version = if (result.ok) parseVersion(result.output) else null
        if (version != null) marker.writeText(version) else marker.delete()
        val next = _state.value.copy(
            version = version,
            message = if (result.ok) null else result.output.ifBlank { "CodeGraph could not be started." },
            failed = !result.ok,
        )
        _state.value = next
        return next
    }

    /**
     * Asks GitHub for the newest release and compares it with what is
     * installed, so the settings page can offer an update only when there is
     * one. Reports the outcome in [CodeGraphState.message] either way, which
     * is what makes an explicit "check" tap answer "already latest".
     */
    suspend fun checkForUpdates(): CodeGraphState {
        val installed = _state.value.version ?: return _state.value
        _state.value = _state.value.copy(busy = true, action = "Checking for updates", message = null, failed = false)
        val latest = withContext(Dispatchers.IO) { resolveTag()?.let { parseVersion(it) } }
        val next = _state.value.copy(
            busy = false,
            action = null,
            latest = latest ?: _state.value.latest,
            message = when {
                latest == null -> "Could not reach GitHub to check for updates."
                CodeGraphProvision.isNewer(latest, installed) -> "CodeGraph $latest is available."
                else -> "CodeGraph $installed is the latest version."
            },
            failed = latest == null,
        )
        _state.value = next
        return next
    }

    suspend fun installOrUpdate(): CodeGraphState = busy("Installing CodeGraph") {
        // The download, the unpack and the hashing all block, and this is
        // reached from the Settings UI's Main-dispatcher scope.
        val failure = withContext(Dispatchers.IO) { provision() }
        if (failure != null) return@busy failure
        val verified = run(CodeGraphCommands.version, home, 60_000, 4_000)
        if (!verified.ok) return@busy verified
        val version = parseVersion(verified.output)
            ?: return@busy CodeGraphCommandResult(false, "CodeGraph installed, but its version could not be verified.")
        marker.writeText(version)
        // Just installed the newest release, so the update check has its answer
        // until the next one lands.
        _state.value = _state.value.copy(latest = version)
        linuxEnv.invalidateExternalToolDeploy()
        CodeGraphCommandResult(true, "CodeGraph $version installed.")
    }

    /** Downloads and lays out the runtime. Null on success, else the failure to report. */
    private suspend fun provision(): CodeGraphCommandResult? {
        linuxEnv.install(listOf("bash"))
        if (!linuxEnv.isReady) {
            return CodeGraphCommandResult(false, "The Linux environment could not be prepared.")
        }
        val tag = resolveTag()
            ?: return CodeGraphCommandResult(
                false,
                "Could not reach GitHub to find the latest CodeGraph release.",
            )
        val work = File(linuxEnv.appPrivateScratch, "codegraph").apply { mkdirs() }
        val archive = File(work, CodeGraphProvision.BUNDLE_ASSET)
        try {
            // Best effort, like upstream's installer: a missing SHA256SUMS
            // never blocks an install, a published one always wins.
            val expected = runCatching { fetchText(CodeGraphProvision.sumsUrl(tag)) }.getOrNull()
                ?.let { CodeGraphProvision.sha256For(it, CodeGraphProvision.BUNDLE_ASSET) }
            setAction("Downloading CodeGraph $tag")
            download(CodeGraphProvision.assetUrl(tag), archive, expected) { percent ->
                setAction("Downloading CodeGraph $tag ($percent%)")
            }
            setAction("Unpacking CodeGraph")
            extractBundle(archive)
        } catch (ce: kotlinx.coroutines.CancellationException) {
            throw ce
        } catch (e: Exception) {
            return CodeGraphCommandResult(false, e.message ?: "Installing CodeGraph failed.")
        } finally {
            archive.delete()
        }

        if (!File(bundleLib, "dist/bin/codegraph.js").isFile) {
            return CodeGraphCommandResult(false, "The CodeGraph archive did not contain its CLI.")
        }
        setAction("Preparing the CodeGraph runtime")
        if (!ensureNodeRuntime()) {
            return CodeGraphCommandResult(false, "Could not install the Node runtime CodeGraph needs.")
        }
        writeLauncher()
        removeLegacyNpmInstall()
        linuxEnv.ensureShims(force = true)
        return null
    }

    suspend fun uninstall(): CodeGraphState = busy("Uninstalling CodeGraph") {
        val existed = binary.exists() || root.exists()
        withContext(Dispatchers.IO) {
            runCatching { root.deleteRecursively() }
            runCatching { binary.delete() }
            removeLegacyNpmInstall()
            marker.delete()
            linuxEnv.ensureShims(force = true)
        }
        linuxEnv.invalidateExternalToolDeploy()
        CodeGraphCommandResult(true, if (existed) "CodeGraph removed." else "CodeGraph is not installed.")
    }

    suspend fun initWorkspace(workspace: WorkspaceFs): CodeGraphCommandResult =
        workspaceCommand(workspace, CodeGraphCommands.init, "Initialize CodeGraph")

    suspend fun syncWorkspace(workspace: WorkspaceFs): CodeGraphCommandResult =
        workspaceCommand(workspace, CodeGraphCommands.sync, "Sync CodeGraph")

    suspend fun reindexWorkspace(workspace: WorkspaceFs): CodeGraphCommandResult =
        workspaceCommand(workspace, CodeGraphCommands.reindex, "Re-index CodeGraph", timeoutMs = 300_000)

    suspend fun disableWorkspace(workspace: WorkspaceFs): CodeGraphCommandResult =
        workspaceCommand(workspace, CodeGraphCommands.uninit, "Disable CodeGraph")

    suspend fun explore(workspace: WorkspaceFs, query: String): CodeGraphCommandResult =
        queryWorkspace(workspace, CodeGraphCommands.explore(query))

    suspend fun node(
        workspace: WorkspaceFs,
        name: String?,
        file: String?,
        offset: Int?,
        limit: Int?,
    ): CodeGraphCommandResult = queryWorkspace(workspace, CodeGraphCommands.node(name, file, offset, limit))

    suspend fun impact(workspace: WorkspaceFs, symbol: String, depth: Int): CodeGraphCommandResult =
        queryWorkspace(workspace, CodeGraphCommands.impact(symbol, depth))

    suspend fun affected(workspace: WorkspaceFs, files: List<String>, depth: Int): CodeGraphCommandResult =
        queryWorkspace(workspace, CodeGraphCommands.affected(files, depth))

    // ------------------------------------------------------------------
    // Provisioning
    // ------------------------------------------------------------------

    /** Latest published release tag, from the redirect first and the API second. */
    private fun resolveTag(): String? {
        val redirect = runCatching {
            val noFollow = client.newBuilder().followRedirects(false).build()
            noFollow.newCall(Request.Builder().url(CodeGraphProvision.latestPageUrl()).build()).execute()
                .use { it.header("Location") }
        }.getOrNull()
        CodeGraphProvision.tagFromRedirect(redirect)?.let { return CodeGraphProvision.normalizeTag(it) }
        val api = runCatching { fetchText(CodeGraphProvision.apiLatestUrl()) }.getOrNull()
        return CodeGraphProvision.normalizeTag(api?.let { CodeGraphProvision.tagFromApi(it) })
    }

    private fun fetchText(url: String): String =
        client.newCall(Request.Builder().url(url).build()).execute().use { response ->
            if (!response.isSuccessful) throw IllegalStateException("HTTP ${response.code} fetching $url")
            response.body?.string() ?: throw IllegalStateException("Empty response from $url")
        }

    private fun download(url: String, dest: File, expectedSha256: String?, onProgress: (Int) -> Unit) {
        dest.parentFile?.mkdirs()
        client.newCall(Request.Builder().url(url).build()).execute().use { response ->
            if (!response.isSuccessful) throw IllegalStateException("HTTP ${response.code} downloading $url")
            val body = response.body ?: throw IllegalStateException("Empty download from $url")
            val total = body.contentLength()
            val digest = MessageDigest.getInstance("SHA-256")
            var read = 0L
            dest.outputStream().use { out ->
                body.byteStream().use { input ->
                    val buf = ByteArray(128 * 1024)
                    while (true) {
                        val n = input.read(buf)
                        if (n < 0) break
                        out.write(buf, 0, n)
                        digest.update(buf, 0, n)
                        read += n
                        if (total > 0) onProgress(((read * 100) / total).toInt())
                    }
                }
            }
            val actual = digest.digest().joinToString("") { "%02x".format(it) }
            if (expectedSha256 != null && !actual.equals(expectedSha256, ignoreCase = true)) {
                dest.delete()
                throw IllegalStateException("Checksum mismatch for ${dest.name}")
            }
        }
    }

    /** Unpacks the portable half of the release archive and swaps it in atomically. */
    private fun extractBundle(archive: File) {
        val staging = File(root, "bundle.new").apply {
            deleteRecursively()
            mkdirs()
        }
        GZIPInputStream(archive.inputStream().buffered()).use { gz ->
            TarArchiveInputStream(gz).use { tar ->
                while (true) {
                    val entry = tar.nextTarEntry ?: break
                    if (entry.isDirectory || entry.isSymbolicLink) continue
                    val rel = CodeGraphProvision.portablePath(entry.name) ?: continue
                    val target = File(staging, rel)
                    target.parentFile?.mkdirs()
                    FileOutputStream(target).use { out -> tar.copyTo(out) }
                    runCatching { Os.chmod(target.absolutePath, entry.mode and 0xFFF) }
                }
            }
        }
        val live = File(root, "bundle")
        val previous = File(root, "bundle.old")
        previous.deleteRecursively()
        if (live.exists()) live.renameTo(previous)
        if (!staging.renameTo(live)) throw IllegalStateException("Could not activate the CodeGraph bundle.")
        previous.deleteRecursively()
    }

    /**
     * Installs the Node runtime CodeGraph runs on, when the prefix has none.
     * Termux's `nodejs-lts` is Node 24, the version the release bundle embeds
     * and the newest CodeGraph accepts: it refuses to start on the 25+ that
     * the prefix's `nodejs` package ships, over a V8 WASM crash it cannot
     * guard against. Extracted on its own instead of installed as a package
     * because it conflicts with that `nodejs`.
     */
    private suspend fun ensureNodeRuntime(): Boolean {
        if (nodeBinary.isFile && nodeBinary.length() > 0) return true
        val work = File(linuxEnv.appPrivateScratch, "codegraph").apply { mkdirs() }
        val deb = File(work, "nodejs-lts.deb")
        return try {
            if (!linuxEnv.downloadPackageDeb(CodeGraphProvision.NODE_PACKAGE, deb)) return false
            extractNodeBinary(deb)
            nodeBinary.isFile && nodeBinary.length() > 0
        } finally {
            deb.delete()
        }
    }

    private fun extractNodeBinary(deb: File) {
        ArArchiveInputStream(deb.inputStream().buffered()).use { ar ->
            var entry = ar.nextEntry
            while (entry != null && !entry.name.startsWith("data.tar")) entry = ar.nextEntry
            if (entry == null) throw IllegalStateException("No data archive in ${deb.name}")
            // Choose the decompressor from the extension, since auto-detection
            // would need a markable stream, which ArArchiveInputStream is not.
            val name = entry.name
            val input: InputStream = when {
                name.endsWith(".xz") || name.endsWith(".lzma") ->
                    CompressorStreamFactory().createCompressorInputStream(CompressorStreamFactory.XZ, ar)
                name.endsWith(".gz") ->
                    CompressorStreamFactory().createCompressorInputStream(CompressorStreamFactory.GZIP, ar)
                name.endsWith(".bz2") ->
                    CompressorStreamFactory().createCompressorInputStream(CompressorStreamFactory.BZIP2, ar)
                name.endsWith(".zst") ->
                    CompressorStreamFactory().createCompressorInputStream(CompressorStreamFactory.ZSTANDARD, ar)
                else -> ar
            }
            TarArchiveInputStream(input).use { tar ->
                while (true) {
                    val e = tar.nextTarEntry ?: break
                    val rel = e.name.removePrefix("./").removePrefix("/")
                    if (rel != "data/data/com.termux/files/usr/bin/node") continue
                    nodeBinary.parentFile?.mkdirs()
                    FileOutputStream(nodeBinary).use { out -> tar.copyTo(out) }
                    runCatching { Os.chmod(nodeBinary.absolutePath, 0x1ED) } // 0755
                }
            }
        }
    }

    private fun writeLauncher() {
        binary.parentFile?.mkdirs()
        // The npm-based install left a symlink here pointing into its package;
        // writing straight to the path would follow it and clobber that file.
        runCatching { binary.delete() }
        binary.writeText(CodeGraphCommands.launcher())
        runCatching { Os.chmod(binary.absolutePath, 0x1ED) } // 0755
    }

    /**
     * Removes what the earlier npm-based install left behind. That route could
     * never work on Android (there is no `codegraph-android-arm64` bundle to
     * install) and the launcher now replaces its entry point, so the shim
     * package is dead weight.
     */
    private fun removeLegacyNpmInstall() {
        runCatching { File(linuxEnv.prefix, "lib/node_modules/@colbymchenry").deleteRecursively() }
    }

    /** Current step, shown under the progress bar while an install runs. */
    private fun setAction(action: String) {
        _state.value = _state.value.copy(action = action)
    }

    // ------------------------------------------------------------------
    // Running
    // ------------------------------------------------------------------

    private suspend fun queryWorkspace(workspace: WorkspaceFs, command: String): CodeGraphCommandResult {
        val ready = requireIndexed(workspace)
        if (ready != null) return ready
        val root = workspace.shellRoot!!
        val synced = run(CodeGraphCommands.sync, root, 180_000, 12_000)
        if (!synced.ok) return CodeGraphCommandResult(false, "CodeGraph sync failed before the query:\n${synced.output}")
        return run(command, root, 180_000, 80_000)
    }

    private suspend fun workspaceCommand(
        workspace: WorkspaceFs,
        command: String,
        label: String,
        timeoutMs: Int = 180_000,
    ): CodeGraphCommandResult {
        val root = workspace.shellRoot
            ?: return CodeGraphCommandResult(false, "CodeGraph needs a workspace with a real filesystem path.")
        if (_state.value.version == null) refresh()
        if (_state.value.version == null) {
            return CodeGraphCommandResult(false, "Install CodeGraph in Settings → Code intelligence first.")
        }
        _state.value = _state.value.copy(busy = true, action = label, message = null, failed = false)
        val result = run(command, root, timeoutMs, 40_000)
        _state.value = _state.value.copy(
            busy = false,
            action = null,
            message = result.output.ifBlank { if (result.ok) "$label complete." else "$label failed." },
            failed = !result.ok,
        )
        return result
    }

    private suspend fun requireIndexed(workspace: WorkspaceFs): CodeGraphCommandResult? {
        val root = workspace.shellRoot
            ?: return CodeGraphCommandResult(false, "CodeGraph needs a workspace with a real filesystem path.")
        if (_state.value.version == null) refresh()
        if (_state.value.version == null) {
            return CodeGraphCommandResult(false, "CodeGraph is not installed. Open Settings → Code intelligence to install it.")
        }
        if (!root.resolve(".codegraph").isDirectory) {
            return CodeGraphCommandResult(false, "CodeGraph is not enabled for this workspace. Open Settings → Code intelligence and enable it first.")
        }
        return null
    }

    private suspend fun busy(label: String, block: suspend () -> CodeGraphCommandResult): CodeGraphState {
        _state.value = _state.value.copy(busy = true, action = label, message = null, failed = false)
        val result = runCatching { block() }.getOrElse {
            CodeGraphCommandResult(false, it.message ?: "$label failed.")
        }
        val refreshedVersion = if (result.ok) {
            if (binary.exists()) {
                val versionResult = run(CodeGraphCommands.version, home, 60_000, 4_000)
                if (versionResult.ok) parseVersion(versionResult.output) else markerVersion()
            } else null
        } else markerVersion()
        if (refreshedVersion == null) marker.delete() else marker.writeText(refreshedVersion)
        // Built from the CURRENT state, not the pre-run snapshot, so anything
        // the block recorded (the resolved release) survives. A vanished
        // install has no meaningful "latest" either.
        return _state.value.copy(
            version = refreshedVersion,
            latest = _state.value.latest.takeIf { refreshedVersion != null },
            busy = false,
            action = null,
            message = result.output.ifBlank { if (result.ok) "$label complete." else "$label failed." },
            failed = !result.ok,
        ).also { _state.value = it }
    }

    private suspend fun run(command: String, cwd: File, timeoutMs: Int, maxOutput: Int): CodeGraphCommandResult {
        val result = shellRouter.run(command, cwd, timeoutMs, maxOutput)
        val output = buildString {
            if (result.rawOutput.isNotBlank()) append(result.rawOutput.trimEnd())
            if (result.rawStderr.isNotBlank()) {
                if (isNotEmpty()) append('\n')
                append(result.rawStderr.trimEnd())
            }
            result.note?.let {
                if (isNotEmpty()) append('\n')
                append(it)
            }
        }
        return CodeGraphCommandResult(!result.timedOut && result.exitCode == 0, output)
    }

    private fun markerVersion(): String? =
        runCatching { marker.readText().trim().takeIf { it.isNotEmpty() } }.getOrNull()

    private fun parseVersion(output: String): String? =
        Regex("""\b\d+\.\d+\.\d+(?:[-+][A-Za-z0-9._-]+)?\b""").find(output)?.value
}